/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': 'var(--color-on-primary)',
        'positive-green': 'var(--color-positive-green)',
        'danger-soft': 'var(--color-danger-soft)',
        'brand-blue-text': 'var(--color-brand-blue-text)',
        secondary: 'var(--color-secondary)',
        muted: 'var(--color-muted)',
        'dark-sidebar-active': 'var(--color-dark-sidebar-active)',
        'brand-blue-hover': 'var(--color-brand-blue-hover)',
        'brand-blue-soft': 'var(--color-brand-blue-soft)',
        'dark-sidebar': 'var(--color-dark-sidebar)',
        'danger-text': 'var(--color-danger-text)',
        'text-primary': 'var(--color-text-primary)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'app-bg': 'var(--color-app-bg)',
        'positive-soft': 'var(--color-positive-soft)',
        'warning-text': 'var(--color-warning-text)',
        'dark-sidebar-muted': 'var(--color-dark-sidebar-muted)',
        primary: 'var(--color-primary)',
        'warning-amber': 'var(--color-warning-amber)',
        'danger-red': 'var(--color-danger-red)',
        'dark-sidebar-border': 'var(--color-dark-sidebar-border)',
        'card-bg': 'var(--color-card-bg)',
        'dark-sidebar-hover': 'var(--color-dark-sidebar-hover)',
        'brand-blue-border': 'var(--color-brand-blue-border)',
        'border-subtle': 'var(--color-border-subtle)',
        surface: 'var(--color-surface)',
        'primary-container': 'var(--color-primary-container)',
        'warning-soft': 'var(--color-warning-soft)',
        'warning-border': 'var(--color-warning-border)',
        'danger-border': 'var(--color-danger-border)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'purple-flow': 'var(--color-purple-flow)',
        'purple-soft': 'var(--color-purple-soft)',
      },
      spacing: {
        'space-xs': 'var(--spacing-space-xs)',
        'space-sm': 'var(--spacing-space-sm)',
        'space-md': 'var(--spacing-space-md)',
        'space-lg': 'var(--spacing-space-lg)',
        'space-xl': 'var(--spacing-space-xl)',
        margin: 'var(--spacing-margin)',
        'margin-mobile': 'var(--spacing-margin-mobile)',
      },
      fontFamily: {
        sans: ['Inter', 'System'],
      },
      fontSize: {
        'badge-micro': [
          '10px',
          { lineHeight: '12px', fontWeight: '800', letterSpacing: '0.02em' },
        ],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'title-md': [
          '16px',
          { lineHeight: '22px', fontWeight: '700', letterSpacing: '-0.005em' },
        ],
        'headline-sm': [
          '20px',
          { lineHeight: '26px', fontWeight: '700', letterSpacing: '-0.01em' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '30px', fontWeight: '800', letterSpacing: '-0.015em' },
        ],
        'label-caps': [
          '11px',
          { lineHeight: '14px', fontWeight: '800', letterSpacing: '0.04em' },
        ],
        'label-numeric-md': [
          '14px',
          { lineHeight: '18px', fontWeight: '800' },
        ],
        'label-numeric-lg': [
          '24px',
          { lineHeight: '28px', fontWeight: '800', letterSpacing: '-0.02em' },
        ],
        'display-hero-mobile': [
          '36px',
          { lineHeight: '40px', fontWeight: '900', letterSpacing: '-0.02em' },
        ],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        control: '9px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
